version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./check_backup.backup:/docker-entrypoint-initdb.d/check_backup.backup
    ports:
      - '0.0.0.0:5432:5432'
    networks:
      uzum-parser:
        ipv4_address: 172.18.0.3

  app:
    build: .
    container_name: uuzzuumm_true_shower
    ports:
      - '0.0.0.0:8090:80'
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 80"
    env_file:
      - .env
    volumes:
      - ./fastapi_app.db:/app/fastapi_app.db:delegated
    environment:
      - PYTHONPATH=/app/app
    depends_on:
      - db
    networks:
      uzum-parser:
        ipv4_address: 172.18.0.2
networks:
  uzum-parser:
    driver: bridge
    external: true