version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'

  backend:
    build: .
    container_name: backend
    ports:
      - '8090:80'
    command: bash -c "cd backend;uvicorn main:app --host 0.0.0.0 --port 80"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/backend/backend
    depends_on:
      - db

volumes:
  app_data:


